### ISSUE TITLE
Can't enable gateway

### ISSUE THREAD

**Issue by mashour06** [shazzad/woocommerce-gateway-stcpay#1]
Hello Sir,
I'm trying to enable Woocommerce-gateway-stcpay payment gateway, I set up the plugin and activated it. but when I try to enable the gateway on woocommerce->settings->payment it gets disabled again, and it doesn't show on the checkout page. I entered all info required like merchant ID... etc.
Any help to solve the problem would be greatly appreciated. Thanks in advance.

**Comment by shazzad** [comment]
Did you configured ssl key & certificate file path ?

**Comment by mashour06** [comment]
Hello Sir,
Thank you for your reply. I can now enable the gateway after entering the private key file (this one was missing). But there is another issue, there is an error message stating that: "Could not process your request. Please try later, or use other payment gateway". The log file gives me the following error:
2023-09-15T12:12:13+00:00 INFO Stcpay API Error: cURL error 58: could not load PEM client certificate, OpenSSL error error:0909006C:PEM routines:get_name:no start line, (no key found, wrong pass phrase, or wrong file format?).
I have a .pfx file which I entered its path too. the merchant ID is correct. I tested every thing in postman and every thing is working properly. but from the website it's not working. I'm testing on localhost.

**Comment by shazzad** [comment]
I have removed the ssl certificate dependency. Try removing the ssl certificate setting fields value.

**Comment by mashour06** [comment]
I removed the values for the following fields:
Production SSL Cert File
Production SSL Key File
Production SSL Key Password
But unfortunately the problem didn't resolve. Now I get this log error:
INFO Stcpay API Error: Invalid merchant id or ssl certificates

**Comment by shazzad** [comment]
In that case stcpay gateway still requires the ssl certificate files to be defined.

Then you should try to debug your ssl certificate based on the error log you received earlier.
Reference: https://stackoverflow.com/a/63042717

**Comment by mashour06** [comment]
Sir, I entered the path to pfx file like this:
C:\wamp64\www\asfarok_2_9_2023\wp-content\plugins\woocommerce-gateway-stcpay\pfx\asfarokPfx.pfx
Is entering an absolute path like this correct? I'm working on localhost on windows machine.

**Comment by mashour06** [comment]
I changed the pfx file to .pem file and the payment completed without entering the OTP that has been sent to the mobile. the system didn't give me any thing to enter the OTP and the payment completed. What is the problem and how to solve it?

**Comment by mashour06** [comment]
Any help would be greatly appreciated.

**Comment by shazzad** [comment]
Can you shot a video of the whole checkout process ? As far i remember, the OTP should be entered on stcpay hosted confirmation page.

This plugin was developer few years ago, and not maintained with the latest changes.

**Comment by mashour06** [comment]
Hello Sir,
Here is the video and image, the image is a screenshot from the mobile phone with 2 messages: a message with the OTP code, and the other message is indicating that the payment was approved and the order placed (directly without entering the OTP code), and there was no field appeared to enter the OTP code.

https://github.com/shazzad/woocommerce-gateway-stcpay/assets/58418406/e08d9454-6457-453f-982e-a129ba766c64

![stcpay](https://github.com/shazzad/woocommerce-gateway-stcpay/assets/58418406/513bef14-43c1-41cc-93fa-6cf053e467f9)

**Comment by mashour06** [comment]
Hello,
Did you find any solution?

**Comment by amrith-am** [comment]
INFO Stcpay API Error: cURL error 6: Could not resolve host: b2btest.stcpay.com.sa

**Comment by amrith-am** [comment]
I got this error

**Comment by shazzad** [comment]
The error indicates that their testing server url has changed. Please contact with them for the new URL.

Also, it's been a while since this plugin was last updated. If they make changes to their api, the plugin won't work without modification.
